---
title: "Autocorrelation Assessment"
author: "Indigo Edwards"
date: "12/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(lubridate)
library(stringr)
library(corrplot)

cc_sites <- read_csv('data/raw/2021-11-18_Site.csv') %>% 
  filter(
    Name != 'Example Site',
    Latitude < 50)

cc_plants <- read_csv('data/raw/2021-11-18_Plant.csv')

cc_surveys <- read_csv('data/raw/2021-11-18_Survey.csv')

lsm_500m <- read_csv('data/processed/lsm_metrics_500m.csv')

lsm_1000m <- read_csv('data/processed/lsm_metrics_1000m.csv')

lsm_3000m <- read_csv('data/processed/lsm_metrics_3000m.csv')

lsm_5000m <- read_csv('data/processed/lsm_metrics_5000m.csv')

lsm_10000m <- read_csv('data/processed/lsm_metrics_10000m.csv')

pc_500m <- read_csv('data/processed/percent_cover_500m.csv')

pc_1000m <- read_csv('data/processed/percent_cover_1000m.csv')

pc_3000m <- read_csv('data/processed/percent_cover_3000m.csv')

pc_5000m <- read_csv('data/processed/percent_cover_5000m.csv')

pc_10000m <- read_csv('data/processed/percent_cover_10000m.csv')

```


```{r correlation, echo = F}

mapped_list <- map2(
  list(
    pc_500m,pc_1000m,pc_3000m,pc_5000m,pc_10000m,
    lsm_500m,lsm_1000m,lsm_3000m,lsm_5000m,lsm_10000m),
  c('500m','1000m','3000m','5000m','10000m',
    '500m','1000m','3000m','5000m','10000m'),
  function(x,y){
   
    x %>% 
      rename_with(~ str_c(., y, sep = '_'), .cols = 3:length(x)) %>% 
      select(-Name)
      
  })

mapped_list[[1]] %>% 
  full_join(mapped_list[[2]]) %>% 
  full_join(mapped_list[[3]]) %>% 
  full_join(mapped_list[[4]]) %>% 
  full_join(mapped_list[[5]]) %>% 
  full_join(mapped_list[[6]]) %>% 
  full_join(mapped_list[[7]]) %>% 
  full_join(mapped_list[[8]]) %>% 
  full_join(mapped_list[[9]]) %>% 
  full_join(mapped_list[[10]]) %>%
  cor(use = 'complete.obs') %>%
  corrplot(method = 'color')

```


Next steps: 

1. Run correlation matrix.

2. Start assessing correlations between landscape statistics and CC data - what CC statistics do we want to start with?
